language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "stocks-portfolio-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: stocfolio
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: eCawSot3Odd2TUNG87Re8vSt6RusdzL0qklP6nVh1wR2SiDCTYKiD6F7mzfpsKDW3U2L5Ks/uHYGaQvmi3XC4GBYAturTsqnExgoKldfFU+ocWK0smqSn1yvb/CPq2MWPaTLAKgf5A8t68FCjDD4TXrIXq8epuk55f0LUQOMXzMoj1iXp5ezEoJGFi3NmfFbJvrZn1Dmxt4+sg2RLaCXhR26xDEGcTP0VcrnhtHWAU2ant16PAfICNL5jZ7G2hLc46XCOjMBbPXKXccNq29TL3zhR86o43BSgeE1n/57eDcFhAb0KxhSCIjoag4cIho5rSWPleWGGIPqRt8ZpPZ3ZoCkg6L66nwh+G+rN/Nb30jTNPpM+WCQWyuRpjV2Rw7qd5SN3zD0ShJaZuFFr9t0F/NtMRJGiuIx5gmTCVfTDUQrrDEg4l76C5HAc7OVZTVVbnVm++YaBR//C4AtM+Tr+bCNqVvBTALg/1wdA+WV4M8+UmJ58RJlek7s/cVhQeRksIVXJPePzc01cm0EZHA+TNGND3P7sWSuwKK2p/KtZjymDiSzRJS/+cFmh/V6qfV0KcLxlBHyp7JMc/9/J5BvxJYNC1ZKEK37Z7TSJSpcHfcqkKp7TLum1UEjk1e0eKnpm0062BuSlCIRswE0bLaF7uow2vGKOcxj9N1dH1hJZ8M=
